blank_issues_enabled: false
contact_links:
  - name: Folding@home issue tracker
    url: https://github.com/FoldingAtHome/fah-issues/issues/new/choose
    about: Please create and discuss issues here.
