#!/bin/bash -e

# fahcontrol preinstall

# pre-delete cruft from old pkg mistakes
# don't try to mv app here; installer won't like it
# at some pont, this will not be reasonable to keep doing

A1="/Applications/Folding@home/FAHControl.app"
A2="/Applications/Folding@home/FAHControl/FAHControl.app"

[ -d "$A1" ] && [ -d "$A2" ] && rm -rf "$A2" || true
